# Site settings
# These are used to personalize your new site.
title: Richard Ocampo # your name here
logo: "/images/397452223_10108993106374906_3277604329565939172_n.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Arts in Applied Computing: Cybersecurity Concentration (class of 2027)
  <br /><br />
  <a href="www.linkedin.com/in/richard-ocampo-74007645">View My LinkedIn Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  richardocampo88 # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

